export const actions = {
	FETCH_USER: 'FETCH_USER',
	FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
	FETCH_USER_FAILED: 'FETCH_USER_FAILED',

	REGISTER_USER: 'REGISTER_USER',
	REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
	REGISTER_USER_FAILED: 'REGISTER_USER_FAILED',

	UPDATE_USER: 'UPDATE_USER',
	UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
	UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',

	DELETE_USER: 'DELETE_USER',
	DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
	DELETE_USER_FAILED: 'DELETE_USER_FAILED',

	UPDATE_MODAL: 'UPDATE_MODAL',
	UPDATE_MODAL_SUCCESS: 'UPDATE_MODAL_SUCCESS',
	UPDATE_MODAL_FAILED: 'UPDATE_MODAL_FAILED',
};
